/*

              ***Challenge 2***
              /**
 * Coded By : Medi W. Assumani
 * Language : Java
 * 
 *          DOCUMENTATION
 *          *************
 * This program finds the sum of the even-valued terms. Each new term in the Fibonacci sequence 
 
 is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 * 
 *              STEPS
 *              *****
 * 
 * 
 * **/
import java.util.*;

public class Problem2{
  
  public static void main(string[] args){

        List<Integers> myList = new Arraylist<Integers>();// array to hold even numbers

    }
  
  public static List<Integer> getFibNumbers(int limit){

        List <Integer> fibNumbers = new ArrayList<Integer>();
        if(limit == 0 || limit == 1){//base case

            return 1;
        }else{
            fibNumbers.add(getFibNumbers(limit - 1) - getFibNumbers(limit - 2));
        };

        return fibNumbers;
    }
  
  
}
