/*
      FIND THE BUG AND COMPLETE TO GET CORRECT RESULT
              ***Challenge 2***
              /**
 * Coded By : Medi W. Assumani
 * Language : Java
 * Program Name : Even Fibonacci numbers
 * 
 *          DOCUMENTATION
 *          *************
 * This program finds the sum of the even-valued terms. Each new term in the Fibonacci sequence 
 
 is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued term

 * **/
import java.util.*;
import java.lang.Math;

public class Problem2{
    
    public static void main(String[] args){
      
        static const int LIMIT = 4000000; // stores the limit condition
      
        List<Integer>fibNumbers = fibSequence(limit);//stores the first 4M fibonacci numbers
      
        List<Integer>evenFib = getEvenNumbers(fibNumbers);//stores the list of even fibonacci numbers
      
        System.out.println(getListSum(evenFib)); // uses the function getListSum to print the sum of the even fib numbers

    }
  
    //function to find the fibonacci numbers given the max/limit number
    //Postcondition : The list of fibonacci numbers is returned
    public static List<Integer> fibSequence(int limit){

        List<Integer> fibValues = new ArrayList<Integer>();

        int a = 0;
        int b = 1;
        int sum = 0;
        int count = 0;

        while(count < limit){
            
            sum = a + b;
            a = b;
            b = sum ;

            fibValues.add(sum);
            count++;
        }

        return fibValues;
    }
 
    //function to get the even fibonacci numbers
    //postcondition : The list of the even numbers in the fibonacci sequence is returned
    public static List<Integer> getEvenNumbers(List<Integer> list){

        List<Integer> evenFib = new ArrayList<Integer>();
        for(int i = 0; i < list.size(); i++){

            if(list.get(i) % 2 == 0){
                evenFib.add(list.get(i));
            }
        }

        return evenFib;
    }
  //function to compute the sum of the even fibonacci numbers
  //postcondition : The sum is returned
    public static long getListSum(List<Integer> list){
        
        long sum = 0;

        for(int i = 0; i < list.size(); i++){
            sum += list.get(i);
        }

        return sum;
    }
}
